### ISSUE TITLE
FrameSet constructor raises different exceptions between releases

### ISSUE THREAD

**Issue by justinfx** [justinfx/fileseq#92]
When the `FrameSet` constructor is passed a sequence containing bad values (strings for instance), we see different exceptions between v1.10.0 and v1.11.0

**Repro**

```python
import fileseq
fileseq.FrameSet(["a", "b"])

```
**v1.10.0**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../fileseq/frameset.py", line 128, in __init__
    self._order = tuple(order)
  File ".../fileseq/utils.py", line 119, in <genexpr>
    return (i for i in chain(*iterables) if i not in seen and not _add(i))
ValueError: invalid literal for int() with base 10: 'a'
```

**v1.11.0**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File .../fileseq/frameset.py", line 139, in __init__
    self._frange = self.framesToFrameRange(
  File ".../fileseq/frameset.py", line 1375, in framesToFrameRange
    ret = ','.join(FrameSet.framesToFrameRanges(frames, zfill))
  File ".../fileseq/frameset.py", line 1262, in framesToFrameRanges
    curr_stride = abs(curr_frame-curr_start)
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

In either case the proper exception should really be a `fileseq.exceptions.ParseException` just like that which is raised when passing a bad single string arg value. We should add the missing tests for bad sequence args, as strings, and ensure it raises the same exception.

**Comment by justinfx** [comment]
Fixed via #93
